import { PriceItemType } from "types/Price"
import PriceTableDesktop from "./PricingTableDesktop/PriceTableDesktop"
import PriceTableMobile from "./PricingTableMobile/PriceTableMobile"

const priceList: PriceItemType[] = [
  {
    name: "Website Live Chat",
    hacker: true,
    startups: true,
    business: true,
    enterprise: true,
    group: "Channels",
  },
  {
    name: "Email",
    hacker: false,
    startups: true,
    business: true,
    enterprise: true,
    group: "Channels",
  },
  {
    name: "Facebook",
    hacker: false,
    startups: true,
    business: true,
    enterprise: true,
    group: "Channels",
  },
  {
    name: "Instagram",
    hacker: false,
    startups: true,
    business: true,
    enterprise: true,
    group: "Channels",
  },
  {
    name: "Twitter",
    hacker: false,
    startups: true,
    business: true,
    enterprise: true,
    group: "Channels",
  },
  {
    name: "WhatsApp",
    hacker: false,
    startups: true,
    business: true,
    enterprise: true,
    group: "Channels",
  },
  {
    name: "SMS",
    hacker: false,
    startups: true,
    business: true,
    enterprise: true,
    group: "Channels",
  },
  {
    name: "Telegram",
    hacker: false,
    startups: true,
    business: true,
    enterprise: true,
    group: "Channels",
  },
  {
    name: "Line",
    hacker: false,
    startups: true,
    business: true,
    enterprise: true,
    group: "Channels",
  },
  {
    name: "API Channel",
    hacker: false,
    startups: true,
    business: true,
    enterprise: true,
    group: "Channels",
  },
  {
    name: "Private Notes",
    hacker: true,
    startups: true,
    business: true,
    enterprise: true,
    group: "Collaboration & Productivity",
  },
  {
    name: "@mentions",
    hacker: true,
    startups: true,
    business: true,
    enterprise: true,
    group: "Collaboration & Productivity",
  },
  {
    name: "Labels",
    hacker: true,
    startups: true,
    business: true,
    enterprise: true,
    group: "Collaboration & Productivity",
  },
  {
    name: "Keyboard Shortcuts",
    hacker: true,
    startups: true,
    business: true,
    enterprise: true,
    group: "Collaboration & Productivity",
  },
  {
    name: "Canned Responses",
    hacker: true,
    startups: true,
    business: true,
    enterprise: true,
    group: "Collaboration & Productivity",
  },
  {
    name: "Command bar",
    hacker: true,
    startups: true,
    business: true,
    enterprise: true,
    group: "Collaboration & Productivity",
  },
  {
    name: "Auto-Assignment",
    hacker: true,
    startups: true,
    business: true,
    enterprise: true,
    group: "Collaboration & Productivity",
  },
  {
    name: "Multi-lingual Support",
    hacker: true,
    startups: true,
    business: true,
    enterprise: true,
    group: "Collaboration & Productivity",
  },
  {
    name: "Custom Views",
    hacker: false,
    startups: true,
    business: true,
    enterprise: true,
    group: "Collaboration & Productivity",
  },
  {
    name: "Custom Filters",
    hacker: false,
    startups: true,
    business: true,
    enterprise: true,
    group: "Collaboration & Productivity",
  },
  {
    name: "Business Hours",
    hacker: false,
    startups: true,
    business: true,
    enterprise: true,
    group: "Collaboration & Productivity",
  },
  {
    name: "Auto-responder",
    hacker: false,
    startups: true,
    business: true,
    enterprise: true,
    group: "Collaboration & Productivity",
  },
  {
    name: "Teams",
    hacker: false,
    startups: false,
    business: true,
    enterprise: true,
    group: "Collaboration & Productivity",
  },
  {
    name: "Automation",
    hacker: false,
    startups: false,
    business: true,
    enterprise: true,
    group: "Collaboration & Productivity",
  },
  {
    name: "Agent Capacity",
    hacker: false,
    startups: false,
    business: false,
    enterprise: true,
    group: "Collaboration & Productivity",
  },
  {
    name: "Contact Segments",
    hacker: false,
    startups: true,
    business: true,
    enterprise: true,
    group: "Manage customer information",
  },
  {
    name: "Contact Notes",
    hacker: false,
    startups: true,
    business: true,
    enterprise: true,
    group: "Manage customer information",
  },
  {
    name: "Campaigns",
    hacker: false,
    startups: true,
    business: true,
    enterprise: true,
    group: "Manage customer information",
  },
  {
    name: "Custom Attributes",
    hacker: false,
    startups: false,
    business: true,
    enterprise: true,
    group: "Manage customer information",
  },
  {
    name: "Pre-Chat Form",
    hacker: false,
    startups: false,
    business: true,
    enterprise: true,
    group: "Manage customer information",
  },
  {
    name: "Slack",
    hacker: true,
    startups: true,
    business: true,
    enterprise: true,
    group: "Integrations",
  },
  {
    name: "DialogFlow",
    hacker: true,
    startups: true,
    business: true,
    enterprise: true,
    group: "Integrations",
  },
  {
    name: "Dashboard Apps",
    hacker: false,
    startups: true,
    business: true,
    enterprise: true,
    group: "Integrations",
  },
  {
    name: "Live View",
    hacker: true,
    startups: true,
    business: true,
    enterprise: true,
    group: "Reports",
  },
  {
    name: "Conversation Reports",
    hacker: false,
    startups: true,
    business: true,
    enterprise: true,
    group: "Reports",
  },
  {
    name: "Agent Reports",
    hacker: false,
    startups: true,
    business: true,
    enterprise: true,
    group: "Reports",
  },
  {
    name: "Inbox Reports",
    hacker: false,
    startups: true,
    business: true,
    enterprise: true,
    group: "Reports",
  },
  {
    name: "Label Reports",
    hacker: false,
    startups: true,
    business: true,
    enterprise: true,
    group: "Reports",
  },
  {
    name: "Team Reports",
    hacker: false,
    startups: true,
    business: true,
    enterprise: true,
    group: "Reports",
  },
  {
    name: "CSAT Reports",
    hacker: false,
    startups: true,
    business: true,
    enterprise: true,
    group: "Reports",
  },
  {
    name: "Downloadable Reports",
    hacker: false,
    startups: true,
    business: true,
    enterprise: true,
    group: "Reports",
  },
  {
    name: "SAML SSO",
    hacker: false,
    startups: false,
    business: false,
    enterprise: true,
    group: "Others",
  },
  {
    name: "Live-chat support",
    hacker: true,
    startups: true,
    business: true,
    enterprise: true,
    group: "Others",
  },
  {
    name: "Priority email support",
    hacker: false,
    startups: true,
    business: true,
    enterprise: true,
    group: "Others",
  },
  {
    name: "Dedicated account manager",
    hacker: false,
    startups: false,
    business: false,
    enterprise: true,
    group: "Others",
  },
  {
    name: "No. of conversations per mont",
    hacker: '500',
    startups: "Unlimited",
    business: "Unlimited",
    enterprise: "Unlimited",
    group: "Others",
  },
  {
    name: "Data retentio",
    hacker: "30 days",
    startups: "Unlimited",
    business: "Unlimited",
    enterprise: "Unlimited",
    group: "Others",
  },
  {
    name: "Remove Branding",
    hacker: false,
    startups: false,
    business: false,
    enterprise: true,
    group: "Others",
  },
  {
    name: "Phone Support",
    hacker: false,
    startups: false,
    business: false,
    enterprise: true,
    group: "Others",
  },
]

const PricingTable = () => {

  return (
    <div className="bg-white">
      <div className="max-w-6xl mx-auto bg-white py-16 sm:py-24 sm:px-6 lg:px-0">
        <PriceTableMobile dataSource={priceList} />
        <PriceTableDesktop dataSource={priceList} />
      </div>
    </div>
  )
}

export default PricingTable
